version: '3.7'
services:
  app:
    container_name: sample
    restart: always
    build: .
    image: 'sample:1.0.0'
    ports:
      - '3000:3000'
    expose:
      - '3000'
    links:
      - mongodb
  mongodb:
    image: 'mongo:latest'
    container_name: sample-mongodb
    ports:
      - '27017:27017'
    expose:
      - '27017'
    environment:
      MONGODB_USER: ''
      MONGODB_PASSWORD: ''
